# Generated by Django 5.2.9 on 2025-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('title', models.CharField(default='ROYAL TOUCHUP', max_length=255)),
                ('subtitle', models.CharField(default='Comfort Meets Creativity', max_length=255)),
                ('description', models.TextField(default='We design spaces that feel good and work well. Personalized interior design tailored to your taste, lifestyle, and budget.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='city',
            field=models.CharField(choices=[('Kalyani', 'Kalyani'), ('Kancharapara', 'Kancharapara'), ('Barrackpore', 'Barrackpore'), ('Naihati', 'Naihati'), ('Krishnanagar', 'Krishnanagar'), ('Kolkata', 'Kolkata')], max_length=100),
        ),
    ]
